### ISSUE TITLE
Localhost Port 8091 Connection Error

### ISSUE THREAD

**Issue by TheRealBane** [cyber-republic/elastos-privnet#20]
On step 4 of setting up the private net blockchain when trying to verify the wallet service is running by checking the pre-loaded main chain wallet, I get the following error: 

curl: (7) Failed to connect to localhost port 8091: Connection refused

**Comment by kpachhai** [comment]
Could you check the logs of that docker container and paste it here? Make sure to format properly.

**Comment by TheRealBane** [comment]
Which docker container should it be? I've printed the list of docker containers but don't see one for port 8091. Sorry, I'm a docker newbie.

**Comment by kpachhai** [comment]
For info on which port is being used by which container, just check README.md. It has all the details. For 8091, Wallet Service REST API Portal: 8091

So, could you do ```docker container logs -f ela-wallet-service``` and paste the output here?

**Comment by TheRealBane** [comment]
Thanks. Here's what was returned: Error: Invalid or corrupt jarfile ./base.api-0.0.6.jar

**Comment by TheRealBane** [comment]
Ok I downloaded a fresh copy of that file off the repository and replaced the file in that folder. I retry test 4 and get the following result "{"result":"java.net.UnknownHostException: ela-mainchain-normal-1","status":400}"

**Comment by TheRealBane** [comment]
I deleted everything and extracted a fresh copy of the entire private net directory. The jar files in wallet-service and did-service come out as being 1kb instead of 28 MB so I suspect either windows defender or my antivirus software are flagging them as malware and modifying them. I downloaded fresh copies of those two specific jar files in both folders, re-ran the docker compose and now I get another error for port 8091.

curl: (52) Empty reply from server

When I print out the logs I get this:

SLF4J: Class path contains multiple SLF4J bindings.

SLF4J: Found binding in [jar:file:/home/elauser/base.api-0.0.6.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]

SLF4J: Found binding in [jar:file:/home/elauser/base.api-0.0.6.jar!/BOOT-INF/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]

SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.

SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

**Comment by TheRealBane** [comment]
And now by opening up a new terminal window and trying again, I get no errors with 8091 anymore. Weird. But I'll take it.

**Comment by kpachhai** [comment]
Ok i have never tested running private net on windows but i have heard other people encountering some issues with running this on docker windows. Perhaps it's windows related. It certainly works 100% if you're doing this on a linux environment like ubuntu though.

However, with that said, we're going to test this on windows so it's supported on windows too.
